src/queries/index.ts, src/sections/CollateralAndLoansSection.tsx
=> feat: add number of borrowers

src/packages/BalancedJs/contracts/IISS.ts, src/packages/BalancedJs/index.ts, src/queries/index.ts, src/sections/CollateralAndLoanSection.tsx
=> fix: icx staking apy

src/queries/index.ts, src/sections/CollateralAndLoanSection.tsx
=> fix: borrowing apy

src/constants/currency.ts, src/queries/index.ts, src/sections/PairSection.tsx, src/utils/index.ts
=> fix volume and fees data

src/queries/index.ts
=> fix token holder data order

src/queries/index.ts
=> fix: dao-fund

src/sections/TokenSection.tsx, src/utils/formatter.ts
=> fix: price decimal place

src/components/AnimatedList/index.tsx, src/hooks/useSort.ts, src/queries/index.ts, src/sections/PairSection.tsx, src/sections/TokenSection.tsx, src/utils/formatter.ts
=> feat: init sorting

src/components/AnimatedList/index.tsx, src/sections/PairSection.tsx, src/sections/TokenSection.tsx
=> feat: tidy up sorting

src/queries/index.ts, src/utils/formatter.ts
=> fix: fix loan baln rewards calculation

src/pages/PerformanceDetails/sections/HoldingsSection/index.tsx, src/pages/PerformanceDetails/utils/index.tsx, src/theme/index.tsx, src/theme/styled.d.ts
=> feat: add 6 month period

src/components/Footer/index.tsx, src/constants/links.ts, src/pages/StatsPage/index.tsx, src/theme/index.tsx, src/theme/styled.d.ts
=> feat: update footer and stats respo layout

public/index.html, src/pages/PerformanceDetails/index.tsx, src/pages/PerformanceDetails/sections/HoldingsSection/index.tsx, src/pages/PerformanceDetails/sections/StabilityFundSection/index.tsx, src/queries/index.ts
=> feat: show limits

src/queries/index.ts
=> Update network fees distribution info

src/components/LineChart/index.tsx, src/components/MultiLineChart/index.tsx
=> Dynamic Y axis for charts

src/constants/tokens.ts, src/pages/PerformanceDetails/sections/HoldingsSection/index.tsx, src/pages/PerformanceDetails/utils/index.tsx, src/queries/blockDetails.ts
=> Refactor dao token holdings

src/pages/PerformanceDetails/sections/HoldingsSection/index.tsx
=> Fix percentage growth calculation

src/pages/PerformanceDetails/sections/HoldingsSection/index.tsx
Accounts for holdings that are currently zero but were non zero in the past
=> Refactor dao holdings

package.json, src/pages/PerformanceDetails/sections/HoldingsSection/index.tsx, src/sections/HoldingsOverviewSection/queries.ts, yarn.lock
=> Fix pol chart

src/sections/HoldingsOverviewSection/BreakdownChart/index.tsx, src/sections/HoldingsOverviewSection/ReserveChart/index.tsx, src/sections/HoldingsOverviewSection/TokensChart/index.tsx, src/sections/HoldingsOverviewSection/index.tsx, src/sections/HoldingsOverviewSection/queries.ts
=> Update holdings breakdown
